//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutelariaRetiro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caixa
    {
        public Caixa()
        {
            this.MovimentoCaixa = new HashSet<MovimentoCaixa>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataAbertura { get; set; }
        public Nullable<System.DateTime> DataFechamento { get; set; }
        public bool Aberto { get; set; }
        public string Obs { get; set; }
    
        public virtual ICollection<MovimentoCaixa> MovimentoCaixa { get; set; }
    }
}
