//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutelariaRetiro.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CutelariaRetiroEntities : DbContext
    {
        public CutelariaRetiroEntities()
            : base("name=CutelariaRetiroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Caixa> Caixa { get; set; }
        public DbSet<EntradaMaterial> EntradaMaterial { get; set; }
        public DbSet<ItemServico> ItemServico { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialServico> MaterialServico { get; set; }
        public DbSet<MovimentoCaixa> MovimentoCaixa { get; set; }
        public DbSet<Servico> Servico { get; set; }
        public DbSet<TipoServico> TipoServico { get; set; }
    }
}
