//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutelariaRetiro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaMaterial
    {
        public int Id { get; set; }
        public int MaterialId { get; set; }
        public System.DateTime Data { get; set; }
        public int Quantidade { get; set; }
        public string Obs { get; set; }
        public string Lote { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
