//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutelariaRetiro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.EntradaMaterial = new HashSet<EntradaMaterial>();
            this.MaterialServico = new HashSet<MaterialServico>();
        }
    
        public int Id { get; set; }
        public string Referencia { get; set; }
        public string Descricao { get; set; }
        public bool Inativo { get; set; }
        public decimal Preco { get; set; }
        public int Estoque { get; set; }
    
        public virtual ICollection<EntradaMaterial> EntradaMaterial { get; set; }
        public virtual ICollection<MaterialServico> MaterialServico { get; set; }
    }
}
