//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutelariaRetiro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimentoCaixa
    {
        public int Id { get; set; }
        public int CaixaId { get; set; }
        public int Tipo { get; set; }
        public int ServicoId { get; set; }
        public decimal Valor { get; set; }
        public string Obs { get; set; }
        public int FormaPagamento { get; set; }
    
        public virtual Caixa Caixa { get; set; }
    }
}
