//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutelariaRetiro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServico
    {
        public TipoServico()
        {
            this.ItemServico = new HashSet<ItemServico>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal Preco { get; set; }
    
        public virtual ICollection<ItemServico> ItemServico { get; set; }
    }
}
